apiVersion: v1
kind: Secret
metadata:
  name: drink-secret
  namespace: christians-drinks
type: Opaque
stringData:
  POSTGRES_DB: drinkmanager
  POSTGRES_USER: drinkmanager
  POSTGRES_PASSWORD: Y29tCRtFkkJ8K8tEYZkN
  APP_ADMIN_USERNAME: admin
  APP_ADMIN_PASSWORD: 14Cj0CwY2Ok1Y43vO5cO
